feat(ci): Add all jobs to pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -9,7 +9,7 @@ build-portal-frontend-test-runner:
   variables:
     KANIKO_BUILD_CONTEXT: "frontend"
     CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/portal-frontend"
-    KANIKO_ARGS: "--target=test --cache=true"
+    KANIKO_ARGS: "--target=test --cache=true --cache-ttl=24h"
 
 
 build-portal-frontend:
@@ -20,7 +20,49 @@ build-portal-frontend:
   variables:
     KANIKO_BUILD_CONTEXT: "frontend"
     CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/portal-frontend"
-    KANIKO_ARGS: "--cache=true"
+    KANIKO_ARGS: "--cache=true --cache-ttl=24h"
+
+
+build-portal-server-test-runner:
+  stage: build
+  extends: .kaniko
+  variables:
+    DOCKERFILE_PATH: "docker/portal-server/Dockerfile"
+    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/portal-server"
+    KANIKO_ARGS: "--target=test --cache=true --cache-ttl=24h"
+
+
+build-portal-server:
+  stage: build
+  extends: .kaniko
+  needs:
+    - build-portal-server-test-runner
+  variables:
+    DOCKERFILE_PATH: "docker/portal-server/Dockerfile"
+    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/portal-server"
+    KANIKO_ARGS: "--cache=true --cache-ttl=24h"
+
+
+build-notification-api-test-runner:
+  stage: build
+  extends: .kaniko
+  variables:
+    DOCKERFILE_PATH: "notifications-api/Dockerfile"
+    KANIKO_BUILD_CONTEXT: "notifications-api"
+    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/notification-api"
+    KANIKO_ARGS: "--target=test --cache=true --cache-ttl=24h"
+
+
+build-notification-api:
+  stage: build
+  extends: .kaniko
+  needs:
+    - build-notification-api-test-runner
+  variables:
+    DOCKERFILE_PATH: "notifications-api/Dockerfile"
+    KANIKO_BUILD_CONTEXT: "notifications-api"
+    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/notification-api"
+    KANIKO_ARGS: "--cache=true --cache-ttl=24h"
 
 
 test-portal-frontend-unit:
@@ -32,6 +74,108 @@ test-portal-frontend-unit:
     - yarn --cwd=/app test:unit
 
 
+test-portal-frontend-e2e:
+  stage: test
+  needs:
+    - job: build-portal-frontend-test-runner
+  image: "$IMAGE_TAG"
+  artifacts:
+    when: always
+    paths:
+      - /app/tests/e2e/videos/**/*.mp4
+      - /app/tests/e2e/screenshots/**/*.png
+  script:
+    - yarn --cwd=/app test:e2e:headless --browser chrome
+
+
+test-portal-server:
+  stage: test
+  needs:
+    - job: build-portal-server-test-runner
+  image: "$IMAGE_TAG"
+  variables:
+    PYTHONPATH: "./python:/usr/lib/python3/dist-packages"
+  script:
+    - pytest unittests
+
+
+test-notification-api:
+  stage: test
+  needs:
+    - job: build-notification-api-test-runner
+  image: "$IMAGE_TAG"
+  script:
+    - cd notifications-api
+    - pytest --cov=app --cov-report=term --cov-report=xml:coverage.xml
+  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
+  artifacts:
+    reports:
+      coverage_report:
+        coverage_format: cobertura
+        path: notifications-api/coverage.xml
+
+
+# Linting related checks and builds
+
+# TODO: The pre-commit image is missing hadolint, that's why we are building our
+# own one here until it is integrated upstream.
+#
+# Compare: https://git.knut.univention.de/univention/dist/docker-services
+
+build-linter:
+  stage: build
+  extends: .kaniko
+  variables:
+    DOCKERFILE_PATH: docker/linter-pre-commit/Dockerfile
+    KANIKO_BUILD_CONTEXT: docker/linter-pre-commit/
+    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/pre-commit"
+
+
+pre-commit-linting:
+  stage: test
+  needs:
+    - job: build-linter
+  image: "$IMAGE_TAG"
+  variables:
+    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
+    PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"
+  cache:
+    paths:
+    - "${PIP_CACHE_DIR}"
+    - "${PRE_COMMIT_HOME}"
+  script:
+    # Compose lint would fail without the referenced env files
+    - for i in docker/.env.*.example; do cp "${i}" "${i/.example}"; done
+    - pre-commit run --all-files
+
+
+commit-message-linting:
+  stage: test
+  image: docker-registry.knut.univention.de/knut/pre-commit:latest
+  rules:
+    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+  variables:
+    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
+    PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"
+  cache:
+    paths:
+    - "${PIP_CACHE_DIR}"
+    - "${PRE_COMMIT_HOME}"
+  script:
+    - |
+      any_failure=0
+      tmp_file="$(mktemp --tmpdir=.)"
+      for x in $(git log --format="%H" "${CI_MERGE_REQUEST_DIFF_BASE_SHA}..${CI_COMMIT_SHA}")
+      do
+          echo "Checking commit message for $x"
+          git log --format="%B" -n 1 "$x" > "$tmp_file"
+          pre-commit run --hook-stage=commit-msg --commit-msg-filename="$tmp_file" \
+              conventional-pre-commit || any_failure=1
+      done
+      rm "$tmp_file"
+      exit "$any_failure"
+
+
 lint-portal-frontend:
   stage: test
   needs:
@@ -39,13 +183,3 @@ lint-portal-frontend:
   image: "$IMAGE_TAG"
   script:
     - yarn --cwd=/app lint
-
-
-
-test-portal-frontend-e2e:
-  stage: test
-  needs:
-    - job: build-portal-frontend-test-runner
-  image: "$IMAGE_TAG"
-  script:
-    - yarn --cwd=/app test:e2e:headless --browser chrome
